### ISSUE TITLE
Adding group name in a comment

### ISSUE THREAD

**Issue by nhoizey** [theKashey/stylelint-semantic-groups#1]
Hi, thanks for this nice project! 🙏

Would it be possible to add an option to automatically add a comment at the beginning of each group, for educational purpose?

**Comment by theKashey** [comment]
There is good news and bad news
- good: technically it is possible
- bad: this solution just provides configuration for [stylelint-order](https://github.com/hudochenkov/stylelint-order), and if you need "group comments" - it has to be supposed by the `lint-order` and it is not.

**Comment by nhoizey** [comment]
Ok, I think understand, thanks.
