### ISSUE TITLE
Logical Properties support

### ISSUE THREAD

**Issue by Semigradsky** [theKashey/stylelint-semantic-groups#2]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

**Comment by theKashey** [comment]
Sounds right. Currently there is only support for inset, and the rest is yet to be added

**Comment by theKashey** [comment]
Implementing and released as `1.1.2`

**Comment by mortyccp** [comment]
Seem `inline-size` and `block-size` is not handled.
