### ISSUE TITLE
`tslib` version is not compatible with `typescript` version

### ISSUE THREAD

**Issue by knikolov-nuvolo** [theKashey/stylelint-semantic-groups#6]
In my project I have several packages using `tslib`.
One of them has a strict dependency on `2.0.1`, while `stylelint-semantic-groups` depends on `^2.0.0`. So `npm` installs version `2.0.1`.

But I get the following error:
```
TypeError: tslib_1.__spreadArray is not a function
    at Object.logicalProperty (.../node_modules/stylelint-semantic-groups/dist/es5/utils.js:6:56)
```

This is the problematic line:
```js
var logicalProperty = function (name) { return tslib_1.__spreadArray([name], logicalPostfixes.map(function (postfix) { return name + postfix; })); };
```

`__spreadArray` is introduced in `typescript v4.2` and `tslib v2.1`.
`stylelint-semantic-groups` has a dependency on `"typescript": "^4.3.2"`, so it requires at least `"tslib": "^2.1.0"`.

If I manually add a strict dependency to `2.1.0` in my project, the issue is gone. But since I do not use it, it does not make sense to have it as a dependency.

Can you please update the dependency in `package.json`.
Just replace:
```json
"tslib": "^2.0.0"
```
with this:
```json
"tslib": "^2.1.0"
```

Thanks!

**Comment by theKashey** [comment]
Thank you for report. The fix was released as a part of `1.1.4`
